package enum

// PermissionCategory represents different types of permissions
type PermissionCategory string

// PermissionName represents unique permission identifiers
type PermissionName string

// PermissionDescription represents permission descriptions
type PermissionDescription string

const (
	//Permission categories
	DEFAULT    PermissionCategory = "DEFAULT"
	CLUSTER    PermissionCategory = "CLUSTER"
	MANAGEMENT PermissionCategory = "MANAGEMENT"
	HELM       PermissionCategory = "HELM"

	//CLUSTER Permission names
	DEFAULT_PERMISSION                PermissionName = "DEFAULT_PERMISSION"
	MANAGE_NAMESPACE                  PermissionName = "MANAGE_NAMESPACE_ENDPOINTS"
	CREATE_NAMESPACE                  PermissionName = "CREATE_K8S_NAMESPACE"
	VIEW_NAMESPACE                    PermissionName = "VIEW_K8S_NAMESPACE"
	UPDATE_NAMESPACE                  PermissionName = "UPDATE_K8S_NAMESPACE"
	DELETE_NAMESPACE                  PermissionName = "DELETE_K8S_NAMESPACE"
	VIEW_DEPLOYMENT                   PermissionName = "VIEW_NAMESPACE_DEPLOYMENT"
	VIEW_REPLICA_SET                  PermissionName = "VIEW_NAMESPACE_REPLICA_SET"
	MANAGE_POD                        PermissionName = "MANAGE_NAMESPACE_POD"
	VIEW_POD                          PermissionName = "VIEW_NAMESPACE_POD"
	MANAGE_DEPLOYMENT                 PermissionName = "MANAGE_NAMESPACE_DEPLOYMENT"
	MANAGE_REPLICA_SET                PermissionName = "MANAGE_NAMESPACE_REPLICA_SET"
	VIEW_STATEFUL_SET                 PermissionName = "VIEW_NAMESPACE_STATEFUL_SET"
	MANAGE_STATEFUL_SET               PermissionName = "MANAGE_NAMESPACE_STATEFUL_SET"
	VIEW_DAEMON_SET                   PermissionName = "VIEW_NAMESPACE_DAEMON_SET"
	MANAGE_DAEMON_SET                 PermissionName = "MANAGE_NAMESPACE_DAEMON_SET"
	VIEW_SECRET                       PermissionName = "VIEW_NAMESPACE_SECRET"
	MANAGE_SECRET                     PermissionName = "MANAGE_NAMESPACE_SECRET"
	VIEW_CONFIG_MAP                   PermissionName = "VIEW_NAMESPACE_CONFIG_MAP"
	MANAGE_CONFIG_MAP                 PermissionName = "MANAGE_NAMESPACE_CONFIG_MAP"
	VIEW_SERVICE_ACCOUNT              PermissionName = "VIEW_NAMESPACE_SERVICE_ACCOUNT"
	MANAGE_SERVICE_ACCOUNT            PermissionName = "MANAGE_NAMESPACE_SERVICE_ACCOUNT"
	VIEW_SERVICE                      PermissionName = "VIEW_NAMESPACE_SERVICE"
	MANAGE_SERVICE                    PermissionName = "MANAGE_NAMESPACE_SERVICE"
	VIEW_INGRESS                      PermissionName = "VIEW_NAMESPACE_INGRESS"
	MANAGE_INGRESS                    PermissionName = "MANAGE_NAMESPACE_INGRESS"
	VIEW_CERTIFICATE                  PermissionName = "VIEW_NAMESPACE_CERTIFICATE"
	MANAGE_CERTIFICATE                PermissionName = "MANAGE_NAMESPACE_CERTIFICATE"
	VIEW_NAMESPACE_ROLE               PermissionName = "VIEW_NAMESPACE_ROLE"
	MANAGE_NAMESPACE_ROLE             PermissionName = "MANAGE_NAMESPACE_ROLE"
	VIEW_NAMESPACE_ROLE_BINDING       PermissionName = "VIEW_NAMESPACE_ROLE_BINDING"
	MANAGE_NAMESPACE_ROLE_BINDING     PermissionName = "MANAGE_NAMESPACE_ROLE_BINDING"
	VIEW_JOB                          PermissionName = "VIEW_NAMESPACE_JOB"
	MANAGE_JOB                        PermissionName = "MANAGE_NAMESPACE_JOB"
	VIEW_CRON_JOB                     PermissionName = "VIEW_NAMESPACE_CRON_JOB"
	MANAGE_CRON_JOB                   PermissionName = "MANAGE_NAMESPACE_CRON_JOB"
	VIEW_NAMESPACE_NETWORK_POLICY     PermissionName = "VIEW_NAMESPACE_NETWORK_POLICY"
	MANAGE_NAMESPACE_NETWORK_POLICY   PermissionName = "MANAGE_NAMESPACE_NETWORK_POLICY"
	VIEW_NAMESPACE_RESOURCE_QUOTA     PermissionName = "VIEW_NAMESPACE_RESOURCE_QUOTA"
	MANAGE_RESOURCE_QUOTA             PermissionName = "MANAGE_NAMESPACE_RESOURCE_QUOTA"
	VIEW_PERSISTENT_VOLUME            PermissionName = "VIEW_K8S_PERSISTENT_VOLUME"
	MANAGE_PERSISTENT_VOLUME          PermissionName = "MANAGE_K8S_PERSISTENT_VOLUME"
	VIEW_PERSISTENT_VOLUME_CLAIM      PermissionName = "VIEW_NAMESPACE_PERSISTENT_VOLUME_CLAIM"
	MANAGE_PERSISTENT_VOLUME_CLAIM    PermissionName = "MANAGE_NAMESPACE_PERSISTENT_VOLUME_CLAIM"
	VIEW_GATEWAY                      PermissionName = "VIEW_NAMESPACE_GATEWAY"
	MANAGE_GATEWAY                    PermissionName = "MANAGE_NAMESPACE_GATEWAY"
	VIEW_VIRTUAL_SERVICE              PermissionName = "VIEW_NAMESPACE_VIRTUAL_SERVICE"
	MANAGE_VIRTUAL_SERVICE            PermissionName = "MANAGE_NAMESPACE_VIRTUAL_SERVICE"
	VIEW_NODES                        PermissionName = "VIEW_K8S_NODES"
	MANAGE_NODE_TAINT                 PermissionName = "MANAGE_K8S_NODE_TAINT"
	DRAIN_NODE                        PermissionName = "DRAIN_K8S_NODE"
	VIEW_CLUSTER_ROLE                 PermissionName = "VIEW_K8S_CLUSTER_ROLE"
	MANAGE_CLUSTER_ROLE               PermissionName = "MANAGE_K8S_CLUSTER_ROLE"
	VIEW_CLUSTER_ROLE_BINDING         PermissionName = "VIEW_K8S_CLUSTER_ROLE_BINDING"
	MANAGE_CLUSTER_ROLE_BINDING       PermissionName = "MANAGE_K8S_CLUSTER_ROLE_BINDING"
	VIEW_STORAGE_CLASS                PermissionName = "VIEW_K8S_STORAGE_CLASS"
	MANAGE_STORAGE_CLASS              PermissionName = "MANAGE_K8S_STORAGE_CLASS"
	VIEW_CUSTOM_RESOURCES             PermissionName = "VIEW_K8S_CUSTOM_RESOURCES"
	MANAGE_CUSTOM_RESOURCES           PermissionName = "MANAGE_K8S_CUSTOM_RESOURCES"
	VIEW_CUSTOM_RESOURCE_DEFINITION   PermissionName = "VIEW_K8S_CUSTOM_RESOURCE_DEFINITION"
	MANAGE_CUSTOM_RESOURCE_DEFINITION PermissionName = "MANAGE_K8S_CUSTOM_RESOURCE_DEFINITION"
	VIEW_LOGS                         PermissionName = "VIEW_LOGS"
	VIEW_ENDPOINTS                    PermissionName = "VIEW_NAMESPACE_ENDPOINTS"
	MANAGE_ENDPOINTS                  PermissionName = "MANAGE_ENDPOINTS_ENDPOINTS"
	VIEW_ENDPOINT_SLICE               PermissionName = "VIEW_NAMESPACE_ENDPOINT_SLICE"
	MANAGE_ENDPOINT_SLICE             PermissionName = "MANAGE_ENDPOINT_SLICE"
	VIEW_PDB                          PermissionName = "VIEW_NAMESPACE_PDB"
	MANAGE_PDB                        PermissionName = "MANAGE_NAMESPACE_PDB"
	VIEW_CONTROLLER_REVISION          PermissionName = "VIEW_NAMESPACE_CONTROLLER_REVISION"
	MANAGE_CONTROLLER_REVISION        PermissionName = "MANAGE_NAMESPACE_CONTROLLER_REVISION"
	VIEW_REPLICATION_CONTROLLER       PermissionName = "VIEW_NAMESPACE_REPLICATION_CONTROLLER"
	MANAGE_REPLICATION_CONTROLLER     PermissionName = "MANAGE_NAMESPACE_REPLICATION_CONTROLLER"

	//MANAGEMENT Permission names
	VIEW_USER   PermissionName = "VIEW_USER"
	MANAGE_USER PermissionName = "MANAGE_USER"

	VIEW_ROLE   PermissionName = "VIEW_ROLE"
	MANAGE_ROLE PermissionName = "MANAGE_ROLE"

	//CLUSTER Permission descriptions
	DEFAULT_PERMISSION_DESCRIPTION                PermissionDescription = "Default permission for basic access"
	MANAGE_NAMESPACE_DESCRIPTION                  PermissionDescription = "Permission to manage namespace endpoints"
	CREATE_NAMESPACE_DESCRIPTION                  PermissionDescription = "Permission to create Kubernetes namespaces"
	VIEW_NAMESPACE_DESCRIPTION                    PermissionDescription = "Permission to view Kubernetes namespaces"
	UPDATE_NAMESPACE_DESCRIPTION                  PermissionDescription = "Permission to update Kubernetes namespaces"
	DELETE_NAMESPACE_DESCRIPTION                  PermissionDescription = "Permission to delete Kubernetes namespaces"
	VIEW_DEPLOYMENT_DESCRIPTION                   PermissionDescription = "Permission to view deployments"
	VIEW_REPLICA_SET_DESCRIPTION                  PermissionDescription = "Permission to view replica sets"
	MANAGE_POD_DESCRIPTION                        PermissionDescription = "Permission to manage pods"
	VIEW_POD_DESCRIPTION                          PermissionDescription = "Permission to view pods"
	MANAGE_DEPLOYMENT_DESCRIPTION                 PermissionDescription = "Permission to manage deployments"
	MANAGE_REPLICA_SET_DESCRIPTION                PermissionDescription = "Permission to manage replica sets"
	VIEW_STATEFUL_SET_DESCRIPTION                 PermissionDescription = "Permission to view stateful sets"
	MANAGE_STATEFUL_SET_DESCRIPTION               PermissionDescription = "Permission to manage stateful sets"
	VIEW_DAEMON_SET_DESCRIPTION                   PermissionDescription = "Permission to view daemon sets"
	MANAGE_DAEMON_SET_DESCRIPTION                 PermissionDescription = "Permission to manage daemon sets"
	VIEW_SECRET_DESCRIPTION                       PermissionDescription = "Permission to view secrets"
	MANAGE_SECRET_DESCRIPTION                     PermissionDescription = "Permission to manage secrets"
	VIEW_CONFIG_MAP_DESCRIPTION                   PermissionDescription = "Permission to view config maps"
	MANAGE_CONFIG_MAP_DESCRIPTION                 PermissionDescription = "Permission to manage config maps"
	VIEW_SERVICE_ACCOUNT_DESCRIPTION              PermissionDescription = "Permission to view service accounts"
	MANAGE_SERVICE_ACCOUNT_DESCRIPTION            PermissionDescription = "Permission to manage service accounts"
	VIEW_SERVICE_DESCRIPTION                      PermissionDescription = "Permission to view services"
	MANAGE_SERVICE_DESCRIPTION                    PermissionDescription = "Permission to manage services"
	VIEW_INGRESS_DESCRIPTION                      PermissionDescription = "Permission to view ingress resources"
	MANAGE_INGRESS_DESCRIPTION                    PermissionDescription = "Permission to manage ingress resources"
	VIEW_CERTIFICATE_DESCRIPTION                  PermissionDescription = "Permission to view certificates"
	MANAGE_CERTIFICATE_DESCRIPTION                PermissionDescription = "Permission to manage certificates"
	VIEW_NAMESPACE_ROLE_DESCRIPTION               PermissionDescription = "Permission to view roles"
	MANAGE_NAMESPACE_ROLE_DESCRIPTION             PermissionDescription = "Permission to manage roles"
	VIEW_NAMESPACE_ROLE_BINDING_DESCRIPTION       PermissionDescription = "Permission to view role bindings"
	MANAGE_NAMESPACE_ROLE_BINDING_DESCRIPTION     PermissionDescription = "Permission to manage role bindings"
	VIEW_JOB_DESCRIPTION                          PermissionDescription = "Permission to view jobs"
	MANAGE_JOB_DESCRIPTION                        PermissionDescription = "Permission to manage jobs"
	VIEW_CRON_JOB_DESCRIPTION                     PermissionDescription = "Permission to view cron jobs"
	MANAGE_CRON_JOB_DESCRIPTION                   PermissionDescription = "Permission to manage cron jobs"
	VIEW_NAMESPACE_NETWORK_POLICY_DESCRIPTION     PermissionDescription = "Permission to view network policies"
	MANAGE_NAMESPACE_NETWORK_POLICY_DESCRIPTION   PermissionDescription = "Permission to manage network policies"
	VIEW_NAMESPACE_RESOURCE_QUOTA_DESCRIPTION     PermissionDescription = "Permission to view resource quotas"
	MANAGE_RESOURCE_QUOTA_DESCRIPTION             PermissionDescription = "Permission to manage resource quotas"
	VIEW_PERSISTENT_VOLUME_DESCRIPTION            PermissionDescription = "Permission to view persistent volumes"
	MANAGE_PERSISTENT_VOLUME_DESCRIPTION          PermissionDescription = "Permission to manage persistent volumes"
	VIEW_PERSISTENT_VOLUME_CLAIM_DESCRIPTION      PermissionDescription = "Permission to view persistent volumes claim"
	MANAGE_PERSISTENT_VOLUME_CLAIM_DESCRIPTION    PermissionDescription = "Permission to manage persistent volumes claim"
	VIEW_GATEWAY_DESCRIPTION                      PermissionDescription = "Permission to view gateways"
	MANAGE_GATEWAY_DESCRIPTION                    PermissionDescription = "Permission to manage gateways"
	VIEW_VIRTUAL_SERVICE_DESCRIPTION              PermissionDescription = "Permission to view virtual services"
	MANAGE_VIRTUAL_SERVICE_DESCRIPTION            PermissionDescription = "Permission to manage virtual services"
	VIEW_NODES_DESCRIPTION                        PermissionDescription = "Permission to view Kubernetes nodes"
	MANAGE_NODE_TAINT_DESCRIPTION                 PermissionDescription = "Permission to manage Kubernetes node taints"
	DRAIN_NODE_DESCRIPTION                        PermissionDescription = "Permission to drain Kubernetes nodes"
	VIEW_CLUSTER_ROLE_DESCRIPTION                 PermissionDescription = "Permission to view Kubernetes cluster roles"
	MANAGE_CLUSTER_ROLE_DESCRIPTION               PermissionDescription = "Permission to manage Kubernetes cluster roles"
	VIEW_CLUSTER_ROLE_BINDING_DESCRIPTION         PermissionDescription = "Permission to view Kubernetes cluster role bindings"
	MANAGE_CLUSTER_ROLE_BINDING_DESCRIPTION       PermissionDescription = "Permission to manage Kubernetes cluster role bindings"
	VIEW_STORAGE_CLASS_DESCRIPTION                PermissionDescription = "Permission to view Kubernetes storage classes"
	MANAGE_STORAGE_CLASS_DESCRIPTION              PermissionDescription = "Permission to manage Kubernetes storage classes"
	VIEW_CUSTOM_RESOURCES_DESCRIPTION             PermissionDescription = "Permission to view Kubernetes custom resources"
	MANAGE_CUSTOM_RESOURCES_DESCRIPTION           PermissionDescription = "Permission to manage Kubernetes custom resources"
	VIEW_CUSTOM_RESOURCE_DEFINATION_DESCRIPTION   PermissionDescription = "Permission to view Kubernetes custom resource definitions"
	MANAGE_CUSTOM_RESOURCE_DEFINATION_DESCRIPTION PermissionDescription = "Permission to manage Kubernetes custom resource definitions"
	VIEW_LOGS_DESCRIPTION                         PermissionDescription = "Permission to view logs"
	VIEW_ENDPOINTS_DESCRIPTION                    PermissionDescription = "Permission to view endpoints"
	MANAGE_ENDPOINTS_DESCRIPTION                  PermissionDescription = "Permission to manage endpoints"
	VIEW_ENDPOINT_SLICE_DESCRIPTION               PermissionDescription = "Permission to view endpoint slices"
	MANAGE_ENDPOINT_SLICE_DESCRIPTION             PermissionDescription = "Permission to manage endpoint slices"
	VIEW_PDB_DESCRIPTION                          PermissionDescription = "Permission to view pod disruption budgets"
	MANAGE_PDB_DESCRIPTION                        PermissionDescription = "Permission to manage pod disruption budgets"
	VIEW_CONTROLLER_REVISION_DESCRIPTION          PermissionDescription = "Permission to view controller revisions"
	MANAGE_CONTROLLER_REVISION_DESCRIPTION        PermissionDescription = "Permission to manage controller revisions"
	VIEW_REPLICATION_CONTROLLER_DESCRIPTION       PermissionDescription = "Permission to view replication controllers"
	MANAGE_REPLICATION_CONTROLLER_DESCRIPTION     PermissionDescription = "Permission to manage replication controllers"

	//MANAGEMENT Permission names
	VIEW_USER_DESCRIPTION   PermissionDescription = "Permission to view user"
	MANAGE_USER_DESCRIPTION PermissionDescription = "Permission to manage user"

	VIEW_ROLE_DESCRIPTION   PermissionDescription = "Permission to view roles"
	MANAGE_ROLE_DESCRIPTION PermissionDescription = "Permission to manage roles"
)
