package enum

// PermissionCategory represents different types of permissions
type PermissionCategory string

// PermissionName represents unique permission identifiers
type PermissionName string

// PermissionDescription represents permission descriptions
type PermissionDescription string

const (
	// Permission categories
	DEFAULT PermissionCategory = "DEFAULT"
	CLUSTER PermissionCategory = "CLUSTER"
	HELM    PermissionCategory = "HELM"

	// Permission names
	DEFAULT_PERMISSION                      PermissionName = "DEFAULT_PERMISSION"
	VIEW_NAMESPACE                          PermissionName = "VIEW_NAMESPACE_ENDPOINTS"
	MANAGE_NAMESPACE                        PermissionName = "MANAGE_NAMESPACE_ENDPOINTS"
	CREATE_K8S_NAMESPACE                    PermissionName = "CREATE_K8S_NAMESPACE"
	VIEW_K8S_NAMESPACE                      PermissionName = "VIEW_K8S_NAMESPACE"
	UPDATE_K8S_NAMESPACE                    PermissionName = "UPDATE_K8S_NAMESPACE"
	DELETE_K8S_NAMESPACE                    PermissionName = "DELETE_K8S_NAMESPACE"
	VIEW_NAMESPACE_DEPLOYMENT               PermissionName = "VIEW_NAMESPACE_DEPLOYMENT"
	VIEW_NAMESPACE_REPLICA_SET              PermissionName = "VIEW_NAMESPACE_REPLICA_SET"
	MANAGE_NAMESPACE_POD                    PermissionName = "MANAGE_NAMESPACE_POD"
	VIEW_NAMESPACE_POD                      PermissionName = "VIEW_NAMESPACE_POD"
	MANAGE_NAMESPACE_DEPLOYMENT             PermissionName = "MANAGE_NAMESPACE_DEPLOYMENT"
	MANAGE_NAMESPACE_REPLICA_SET            PermissionName = "MANAGE_NAMESPACE_REPLICA_SET"
	VIEW_NAMESPACE_STATEFUL_SET             PermissionName = "VIEW_NAMESPACE_STATEFUL_SET"
	MANAGE_NAMESPACE_STATEFUL_SET           PermissionName = "MANAGE_NAMESPACE_STATEFUL_SET"
	VIEW_NAMESPACE_DAEMON_SET               PermissionName = "VIEW_NAMESPACE_DAEMON_SET"
	MANAGE_NAMESPACE_DAEMON_SET             PermissionName = "MANAGE_NAMESPACE_DAEMON_SET"
	VIEW_NAMESPACE_SECRET                   PermissionName = "VIEW_NAMESPACE_SECRET"
	MANAGE_NAMESPACE_SECRET                 PermissionName = "MANAGE_NAMESPACE_SECRET"
	VIEW_NAMESPACE_CONFIG_MAP               PermissionName = "VIEW_NAMESPACE_CONFIG_MAP"
	MANAGE_NAMESPACE_CONFIG_MAP             PermissionName = "MANAGE_NAMESPACE_CONFIG_MAP"
	VIEW_NAMESPACE_SERVICE_ACCOUNT          PermissionName = "VIEW_NAMESPACE_SERVICE_ACCOUNT"
	MANAGE_NAMESPACE_SERVICE_ACCOUNT        PermissionName = "MANAGE_NAMESPACE_SERVICE_ACCOUNT"
	VIEW_NAMESPACE_SERVICE                  PermissionName = "VIEW_NAMESPACE_SERVICE"
	MANAGE_NAMESPACE_SERVICE                PermissionName = "MANAGE_NAMESPACE_SERVICE"
	VIEW_NAMESPACE_INGRESS                  PermissionName = "VIEW_NAMESPACE_INGRESS"
	MANAGE_NAMESPACE_INGRESS                PermissionName = "MANAGE_NAMESPACE_INGRESS"
	VIEW_NAMESPACE_CERTIFICATE              PermissionName = "VIEW_NAMESPACE_CERTIFICATE"
	MANAGE_NAMESPACE_CERTIFICATE            PermissionName = "MANAGE_NAMESPACE_CERTIFICATE"
	VIEW_NAMESPACE_ROLE                     PermissionName = "VIEW_NAMESPACE_ROLE"
	MANAGE_NAMESPACE_ROLE                   PermissionName = "MANAGE_NAMESPACE_ROLE"
	VIEW_NAMESPACE_ROLE_BINDING             PermissionName = "VIEW_NAMESPACE_ROLE_BINDING"
	MANAGE_NAMESPACE_ROLE_BINDING           PermissionName = "MANAGE_NAMESPACE_ROLE_BINDING"
	VIEW_NAMESPACE_JOB                      PermissionName = "VIEW_NAMESPACE_JOB"
	MANAGE_NAMESPACE_JOB                    PermissionName = "MANAGE_NAMESPACE_JOB"
	VIEW_NAMESPACE_CRON_JOB                 PermissionName = "VIEW_NAMESPACE_CRON_JOB"
	MANAGE_NAMESPACE_CRON_JOB               PermissionName = "MANAGE_NAMESPACE_CRON_JOB"
	VIEW_NAMESPACE_NETWORK_POLICY           PermissionName = "VIEW_NAMESPACE_NETWORK_POLICY"
	MANAGE_NAMESPACE_NETWORK_POLICY         PermissionName = "MANAGE_NAMESPACE_NETWORK_POLICY"
	VIEW_NAMESPACE_RESOURCE_QUOTA           PermissionName = "VIEW_NAMESPACE_RESOURCE_QUOTA"
	MANAGE_NAMESPACE_RESOURCE_QUOTA         PermissionName = "MANAGE_NAMESPACE_RESOURCE_QUOTA"
	VIEW_NAMESPACE_PERSISTENT_VOLUME        PermissionName = "VIEW_NAMESPACE_PERSISTENT_VOLUME"
	MANAGE_NAMESPACE_PERSISTENT_VOLUME      PermissionName = "MANAGE_NAMESPACE_PERSISTENT_VOLUME"
	VIEW_NAMESPACE_GATEWAY                  PermissionName = "VIEW_NAMESPACE_GATEWAY"
	MANAGE_NAMESPACE_GATEWAY                PermissionName = "MANAGE_NAMESPACE_GATEWAY"
	VIEW_NAMESPACE_VIRTUAL_SERVICE          PermissionName = "VIEW_NAMESPACE_VIRTUAL_SERVICE"
	MANAGE_NAMESPACE_VIRTUAL_SERVICE        PermissionName = "MANAGE_NAMESPACE_VIRTUAL_SERVICE"
	VIEW_K8S_NODES                          PermissionName = "VIEW_K8S_NODES"
	MANAGE_K8S_NODE_TAINT                   PermissionName = "MANAGE_K8S_NODE_TAINT"
	DRAIN_K8S_NODE                          PermissionName = "DRAIN_K8S_NODE"
	VIEW_K8S_PERSISTENT_VOLUME              PermissionName = "VIEW_K8S_PERSISTENT_VOLUME"
	MANAGE_K8S_PERSISTENT_VOLUME            PermissionName = "MANAGE_K8S_PERSISTENT_VOLUME"
	VIEW_K8S_CLUSTER_ROLE                   PermissionName = "VIEW_K8S_CLUSTER_ROLE"
	MANAGE_K8S_CLUSTER_ROLE                 PermissionName = "MANAGE_K8S_CLUSTER_ROLE"
	VIEW_K8S_CLUSTER_ROLE_BINDING           PermissionName = "VIEW_K8S_CLUSTER_ROLE_BINDING"
	MANAGE_K8S_CLUSTER_ROLE_BINDING         PermissionName = "MANAGE_K8S_CLUSTER_ROLE_BINDING"
	VIEW_K8S_STORAGE_CLASS                  PermissionName = "VIEW_K8S_STORAGE_CLASS"
	MANAGE_K8S_STORAGE_CLASS                PermissionName = "MANAGE_K8S_STORAGE_CLASS"
	VIEW_K8S_CUSTOM_RESOURCES               PermissionName = "VIEW_K8S_CUSTOM_RESOURCES"
	MANAGE_K8S_CUSTOM_RESOURCES             PermissionName = "MANAGE_K8S_CUSTOM_RESOURCES"
	VIEW_K8S_CUSTOM_RESOURCE_DEFINATION     PermissionName = "VIEW_K8S_CUSTOM_RESOURCE_DEFINATION"
	MANAGE_K8S_CUSTOM_RESOURCE_DEFINATION   PermissionName = "MANAGE_K8S_CUSTOM_RESOURCE_DEFINATION"
	VIEW_LOGS                               PermissionName = "VIEW_LOGS"
	VIEW_NAMESPACE_ENDPOINTS                PermissionName = "VIEW_NAMESPACE_ENDPOINTS"
	MANAGE_NAMESPACE_ENDPOINTS              PermissionName = "MANAGE_NAMESPACE_ENDPOINTS"
	VIEW_NAMESPACE_ENDPOINT_SLICE           PermissionName = "VIEW_NAMESPACE_ENDPOINT_SLICE"
	VIEW_NAMESPACE_PDB                      PermissionName = "VIEW_NAMESPACE_PDB"
	MANAGE_NAMESPACE_PDB                    PermissionName = "MANAGE_NAMESPACE_PDB"
	VIEW_NAMESPACE_CONTROLLER_REVISION      PermissionName = "VIEW_NAMESPACE_CONTROLLER_REVISION"
	MANAGE_NAMESPACE_CONTROLLER_REVISION    PermissionName = "MANAGE_NAMESPACE_CONTROLLER_REVISION"
	VIEW_NAMESPACE_REPLICATION_CONTROLLER   PermissionName = "VIEW_NAMESPACE_REPLICATION_CONTROLLER"
	MANAGE_NAMESPACE_REPLICATION_CONTROLLER PermissionName = "MANAGE_NAMESPACE_REPLICATION_CONTROLLER"

	VIEW_ENDPOINT_SLICE   PermissionName = "VIEW_ENDPOINT_SLICE"
	MANAGE_ENDPOINT_SLICE PermissionName = "MANAGE_ENDPOINT_SLICE"
	VIEW_PDB              PermissionName = "VIEW_PDB"
	MANAGE_PDB            PermissionName = "MANAGE_PDB"

	// Permission descriptions
	DEFAULT_PERMISSION_DESCRIPTION    PermissionDescription = "DEFAULT_PERMISSION"
	VIEW_NAMESPACE_DESCRIPTION        PermissionDescription = "Permission to view namespace endpoints"
	MANAGE_NAMESPACE_DESCRIPTION      PermissionDescription = "Permission to manage namespace endpoints"
	VIEW_ENDPOINT_SLICE_DESCRIPTION   PermissionDescription = "Permission to view endpoint slices"
	MANAGE_ENDPOINT_SLICE_DESCRIPTION PermissionDescription = "Permission to manage endpoint slices"
	VIEW_PDB_DESCRIPTION              PermissionDescription = "Permission to view PDBs"
	MANAGE_PDB_DESCRIPTION            PermissionDescription = "Permission to manage PDBs"
)
