name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Install dependencies (if required)
      - name: Install dependencies
        run: go mod tidy

      # Run unit tests
      - name: Run unit tests
        run: go test ./... -v -coverprofile=coverage.txt

      # Upload coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: krack8/lighthouse
