name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl -LO "https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz"
          tar -zxvf helm-v3.14.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      # Install Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      # Create a Kind Cluster
      - name: Create Kind Cluster
        run: |
          kind create cluster --name lighthouse

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Install dependencies (if required)
      - name: Install dependencies
        run: go mod tidy

      # Run unit tests
      - name: Run unit tests
        run: go test ./... -v -coverprofile=coverage.txt

      # Upload coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: krack8/lighthouse
